# This feature is in Beta.

# Please report any bugs to https://github.com/astronomer/astro-cli/issues

# NOTE: If putting a dict in conn_extra, please wrap in single quotes.

airflow:
  connections:
    - conn_id: "fs_default"
      conn_type: "fs"
      conn_host:
      conn_login:
      conn_password:
      conn_port:
      conn_extra: '{"path":"/tmp/"}'
    - conn_id: "postgres_default"
      conn_type: "postgres"
      conn_host: "192.168.20.31"
      conn_login: "postgres"
      conn_password: "postgres"
      conn_port: "5433"
      conn_extra: ""
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: